// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "WfsIface.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

class WfsIfaceHandler : virtual public WfsIfaceIf {
 public:
  WfsIfaceHandler() {
    // Your initialization goes here
  }

  void Append(WfsAck& _return, const WfsFile& file) {
    // Your implementation goes here
    printf("Append\n");
  }

  void Delete(WfsAck& _return, const std::string& path) {
    // Your implementation goes here
    printf("Delete\n");
  }

  void Rename(WfsAck& _return, const std::string& path, const std::string& newpath) {
    // Your implementation goes here
    printf("Rename\n");
  }

  void Auth(WfsAck& _return, const WfsAuth& wa) {
    // Your implementation goes here
    printf("Auth\n");
  }

  void Get(WfsData& _return, const std::string& path) {
    // Your implementation goes here
    printf("Get\n");
  }

  void List(DirList& _return, const std::string& path) {
    // Your implementation goes here
    printf("List\n");
  }

  int8_t Ping() {
    // Your implementation goes here
    printf("Ping\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  ::std::shared_ptr<WfsIfaceHandler> handler(new WfsIfaceHandler());
  ::std::shared_ptr<TProcessor> processor(new WfsIfaceProcessor(handler));
  ::std::shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  ::std::shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  ::std::shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

